dns: fix compilation error
	# yunion.io/x/onecloud/pkg/dns
	pkg/dns/dns.go:237:44: cannot use "" (type string) as type mcclient.IIdentityProvider in argument to models.HostManager.SEnabledStatusStandaloneResourceBaseManager.SStatusStandaloneResourceBaseManager.SStandaloneResourceBaseManager.FetchByName:
		string does not implement mcclient.IIdentityProvider (missing GetProjectId method)