httperrors: fix formating error messages
Fixes 65880ff8 ("mcclient error")

Before and after

	JSONClientError: certificate 55858afc-de3f-4d14-8e09-3de7cd9b8e2c is still referred to by 1 loadbalancerlisteners%!(EXTRA []interface {}=[])
	JSONClientError: certificate 55858afc-de3f-4d14-8e09-3de7cd9b8e2c is still referred to by 1 loadbalancerlisteners